### ISSUE TITLE
Lua Script Errors

### ISSUE THREAD

**Issue by Zeentch** [wyanido/pokebot-nds#13]
So i've hunted my shiny starter and i'm now attempting to do normal shiny hunting but every random encounter i choose that has to do with wild pokemon doesn't seem to work...

Random Encounters while spinning or running gives me 

Bot mode set to spin_to_win
No function found for mode 'spin_to_win'

Bot mode set to random_encounters_running
No function found for mode 'random_encounters_running'

Random encounters - Horizontal or Vertical gives

Bot mode set to random_encounters
Attempting to start a battle...
NLua.Exceptions.LuaScriptException:
attempt to compare nil with number

This is all on Pokemon White, and i've tried messing with almost all of the settings on the config page on dashboard to see if there is anything there that is conflicting with the script.

While waiting for response / fix for this i'll just start hunting a shiny in HGSS since the shiny in White took almost 3 days.

Thanks for a great project still. :)

**Comment by zenatx** [comment]
Also having this issue on pokemon white

**Comment by wyanido** [comment]
This has since been solved with existing updates
