### ISSUE TITLE
Starters HeartGold

### ISSUE THREAD

**Issue by Phosky71** [wyanido/pokebot-nds#19]
How am I supposed to use the script to make shiny hunt from the starters?

**Comment by wyanido** [comment]
Save the game while facing the machine that contains the starters, then start the script with the mode set to 'Starters'. The bot will hunt all 3 simultaneously and stop on the first one, unless you have specified a specific starter in the config's 'target traits' field.

Ask any future questions in the [Pokébot server](https://discord.com/invite/UtxR3cazUa) for faster support.
