### ISSUE TITLE
Bug with random_encounters in pokemon white

### ISSUE THREAD

**Issue by zenatx** [wyanido/pokebot-nds#22]
Pokébot NDS v0.7.0-alpha by NIDO (wyanido)
https://github.com/wyanido/pokebot-nds

Detected Game: Pokemon White Version

Trying to establish a connection to the dashboard... Connected!
Waiting for dashboard to relay bot configuration... Initialised!
---------------------------
- Party updated
Bot mode set to random_encounters
Attempting to start a battle...
NLua.Exceptions.LuaScriptException: lua\methods\gen_v.lua:816: attempt to call a nil value (global 'frames_per_move')

this is the error I receive when trying to use for random encounters

**Comment by wyanido** [comment]
This has already been fixed, please use the latest version
