### ISSUE TITLE
Getting stuck releasing hatched eggs

### ISSUE THREAD

**Issue by Sourmilk8088** [wyanido/pokebot-nds#25]
Playing Black 2 (USA, EUR), and the bot always gets stuck trying to release pokemon it's hatched - Most of the time it can't find the PC box, gets confused about 3 squares away, and opens a menu, but on the chance it manages to access the PC and dump the pokemon, it'll just get stuck walking into an NPC. Seems to have trouble navigating the building. Pic attached. 

![Eggo](https://github.com/wyanido/pokebot-nds/assets/46482414/c560b9ba-a6be-4a78-aaa2-360438545cd9)

**Comment by Sourmilk8088** [comment]
Bot can get stuck on the NPC in building in White 1 as well
![image](https://github.com/wyanido/pokebot-nds/assets/46482414/41d7ea35-48cd-49fb-9ffc-c94596171cd0)

**Comment by wyanido** [comment]
Fixed on the latest dev commit
