### ISSUE TITLE
Pt egg hatching 

### ISSUE THREAD

**Issue by Sourmilk8088** [wyanido/pokebot-nds#28]
Hatching Rotom in Pt, everytime an egg hatches the bot stops, and gives the same error message: "NLua.Exceptions.LuaScriptException: lua\methods\gen_iv.lua:176: attempt to index a nil value (field '?')"

This occurs with target traits containing only iv_sum: 180, or with only Shiny: True.
They are completely different instances of emuhawk / the script.

![image](https://github.com/wyanido/pokebot-nds/assets/46482414/97591ba1-3732-4133-a49c-739fbe13f708)

**Comment by wyanido** [comment]
Fixed. But as a side note, you should use ivSum instead of iv_sum otherwise the IVs won't be checked correctly.
