### ISSUE TITLE
Pt egg hatching not able to check target fields(?)

### ISSUE THREAD

**Issue by Sourmilk8088** [wyanido/pokebot-nds#29]
On the first egg hatch, consolre reports "# Unknown field Shiny in ruleset #" , then "Rotom is a target!
##### BOT TASK ENDED #####
NLua.Exceptions.LuaScriptException: lua\helpers.lua:136: Hatched a target Pokemon!"
Rotom not listed as target, screenie attached.

![image](https://github.com/wyanido/pokebot-nds/assets/46482414/561c9a29-061f-4cdb-b182-b0c424a5b4e0)

**Comment by wyanido** [comment]
Not a bug, please check your target traits. 'Shiny' is not valid field in the pokemon data, but 'shiny' is.

**Comment by Sourmilk8088** [comment]
Ah, I see. The info bubble for target traits implies it is not case sensitive, hence my confusion :)
