### ISSUE TITLE
Getting stuck releasing in SS

### ISSUE THREAD

**Issue by Sourmilk8088** [wyanido/pokebot-nds#30]
Bot is getting stuck releasing pokemon in Soulsilver after hatching eggs - It more often seems to get stuck at the PC box hovering over "Bills PC", but can also get stuck walking into daycare man outside. Script still running, v1.0.2.

![image](https://github.com/wyanido/pokebot-nds/assets/46482414/f9dc637e-232a-4588-a3b3-52820f6011d1)

**Comment by wyanido** [comment]
I was able to run SoulSilver for 400 egg hatches before manually stopping. Can you post a video example of this?

**Comment by Sourmilk8088** [comment]
I've found the option to "display input", how do I enable debug mode? I'll try to reproduce it as such now :)

**Comment by Sourmilk8088** [comment]
https://github.com/wyanido/pokebot-nds/assets/46482414/48f120fe-7247-4cf4-8d8e-8884d6b33551

(After this they just continued driving into Daycare man)

**Comment by Sourmilk8088** [comment]
https://drive.google.com/file/d/1xbAHdXF6DiPa3RhVT-glrHsvlEL8N_Th/view?usp=sharing

Another shot, this time throttled to make it easier for you to see the inputs.

**Comment by wyanido** [comment]
Thanks for the extra insight, let me know if it's working as of v1.0.3.

**Comment by Sourmilk8088** [comment]
Tried a couple attempts with V1.0.3, now seems to release the party pokemon, but still gets stuck over "Bills PC" - have multiple instances stuck on the same spot. Got a video of it in action before setting up 1.0.4 - Anecdotally, it's always been 2/3 so far.
Video attached with painfully slow throttling, hope it helps!
Also, haven't had Pt or B2 skip a beat hatching since their last updates, can't fault them at all!

https://drive.google.com/file/d/1BN3ytjCAnBW_pSUHCqpCGPW-MAIP4QKU/view?usp=sharing

**Comment by wyanido** [comment]
Made a very small tweak to the PC interaction timing in v1.0.5, let me know if the results are any better.

**Comment by wyanido** [comment]
Assuming all is well following the last change. Don't hesitate to post again if the issue can still be reproduced.

**Comment by Sourmilk8088** [comment]
Sorry, life got in in the way the last few days. i'll give it a good test today, thankyou! <3
