### ISSUE TITLE
NLua.Exceptions.LuaScriptException: lua\helpers.lua:136

### ISSUE THREAD

**Issue by SilverAsh00** [wyanido/pokebot-nds#31]
I setup a fresh HG rom on bizhawk, ran the bot with default settings, right after getting the ability to catch pokemon and i get the error in the title. The pokemon is fully healed, and i have a second one ready to go as well. 
![1](https://github.com/wyanido/pokebot-nds/assets/88670869/6c1b3ed9-e372-4ea8-85eb-71e1fc136955)

**Comment by wyanido** [comment]
Fixed in v1.0.4-beta
