### ISSUE TITLE
Thundurus/Tornadus white/black

### ISSUE THREAD

**Issue by Boosolomon** [wyanido/pokebot-nds#33]
when I launch the bot it gives me the following:
Bot mode set to thundurus_tornadus
Thundurus was not a target, resetting...
Tried to parse data of a non-existent Pokemon! 
Tried to log a non-existent PokÃ©mon! 
lua\methods\gen_v.lua:467: attempt to index local 'mon' (a nil value)
script stopped.

**Comment by wyanido** [comment]
Hi, could you provide some extra info?

1. Game name and language
2. Emulator version
3. Video footage, or preferably a Save State where the bug be reproduced

**Comment by Boosolomon** [comment]
For the version it is both white and black. In the dashboard  I coose the thundurus/tornadus mode then excute the script

https://github.com/wyanido/pokebot-nds/assets/154277594/07f96a2d-5228-4452-bdc7-1935c85c26aa

the video shows what happens in the emulator and the screen what the happens for the  script
![screenshot](https://github.com/wyanido/pokebot-nds/assets/154277594/04f36c71-084d-49c4-9220-6136e464c0e3)

**Comment by wyanido** [comment]
Not a bug. You need to start the script after saving inside of the house before the initial encounter.

**Comment by Boosolomon** [comment]
thanks

**Comment by SpaidsSpaids** [comment]
Hey How did you end up getting this to work? I have the same issue and save inside of the hose right in front of the door ? I run the script and immediately get the same issue and errors
