### ISSUE TITLE
Getting stuck on memories while soft resetting

### ISSUE THREAD

**Issue by Sourmilk8088** [wyanido/pokebot-nds#34]
The bot can soft reset repeatedly, checking for targets, but sometimes gets stuck on the "resume" diary thing at game load.  The "Resume" menu only sometimes appears, which I think is confusing the bot.
It does seem that the bot can get in to a groove of soft resetting without it appearing - but at some point, the "Resume" thing can be triggered, and the bot then can't click through it (Closing this "Resume" diary requires pressing "Start".) I have also tried toggling the script at different points in the games startup process, but this doesn't seem to change anything.

**Platform**
Game: Platinum (EUR)
Language: ENG
Emulator and Version: Emuhawk 2.9.1
Hunting: Heatran (Static SR)

For the following screenshot, I had these instances running overnight - They had (largely) run the last 16 hours without hitching, but in the last 8~ hours, all encountered this menu and got stuck. For the video, selecting "Hard reset" normally fixes it - this time, "reboot core" fixed it instead. I have also seen this happen with Uxie before. I don't have a video of an instance getting stuck - let me know if I can export a log or anything.

My only immediate guess is that this "Resume" appearing happens on full resets but not soft resets or something - I'm really struggling to find documentation on the "Resume" feature, to help reproduce the issue.

![image](https://github.com/wyanido/pokebot-nds/assets/46482414/f84e1b1c-7d95-4576-a680-2ed277342e99)
(All scripts were still playing, they had not paused.)

https://drive.google.com/file/d/1rhUZ_yfOdjyVcf8XULwDrPHH3k0d1w85/view?usp=sharing
(Ignore instance 2nd from the left, that one fully gave up aha.)

**Comment by wyanido** [comment]
This _is_ avoidable by re-saving once every day, but I do agree that it should be fixed outright for convenience.

**Comment by Sourmilk8088** [comment]
Ah, does it only occur once the first time for the new day or something?

**Comment by wyanido** [comment]
Should be resolved as of v1.1-beta
