### ISSUE TITLE
Pokemon Platinum Japan version starters mode not reset game

### ISSUE THREAD

**Issue by wutkaru** [wyanido/pokebot-nds#39]
**Describe the bug**
Staters mode not reset game when pickup one of starter in Japan version then battle with rival and go to home
but US version is work as well

**Platform**
Game: Pokemon Platinum
Language: Japan
Emulator and Version: DeSmuME_0.9.13_x64

**Debug log**
Japan version
![image](https://github.com/wyanido/pokebot-nds/assets/43336971/b7b713fe-20c2-478a-ba65-39d89289047d)

US version
![image](https://github.com/wyanido/pokebot-nds/assets/43336971/b1d70ba2-b222-4015-baa7-461aaa8a7128)

**Config**
![image](https://github.com/wyanido/pokebot-nds/assets/43336971/80df3bbd-4b44-4485-a873-5e5f2f109a46)

**Video**
Japan version
https://github.com/wyanido/pokebot-nds/assets/43336971/75eddefb-c306-4e44-aa51-91c7d8cdc02d

US version
https://github.com/wyanido/pokebot-nds/assets/43336971/2ce6d492-c3cd-4566-81b1-fc3912193258

**Comment by wyanido** [comment]
Working as of v.1.1-beta
