### ISSUE TITLE
Problem with Random Encounters in SS

### ISSUE THREAD

**Issue by miXXed1805** [wyanido/pokebot-nds#40]
**Describe the bug**
I set the bot to Random Encounter right after getting my shiny encounter, and I wanted to continue on the next route immediately. However, the bot keeps switching back and forth between the run and Pokémon tabs.

**Platform**
Game: SS
Language: German
Emulator and Version: BizHawk latest release.

**Example**

https://github.com/wyanido/pokebot-nds/assets/174362347/badcc67d-a036-4649-a0d5-626566fa8c43

**Comment by wyanido** [comment]
Working as of v1.1-beta
