### ISSUE TITLE
Heart Gold Starters not working

### ISSUE THREAD

**Issue by Yansimspoketale** [wyanido/pokebot-nds#44]
**Describe the bug**
As you all can see in the video attached, whenever I try to do the starters reset in heart gold the bot checks the starters, resets but then doesn't go past the title screen by itself, Ok so I have tried a US rom and it works fine there but not on my french rom
**Platform**
Game:Heart Gold
Language:FR
Emulator and Version: DeSmuME_0.9.13

https://github.com/user-attachments/assets/13e6c4b5-04c5-4692-bcdb-6fcf1349c73b

**Comment by wyanido** [comment]
Working as of v1.1-beta
